import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { LoadingPage } from "../components/loading";
import { Feed } from "../components/feed";
import { CreatePostWizard } from "../components/create-post-wizard";

const Home: NextPage = () => {
  const { isSignedIn, isLoaded: userLoaded } = useUser();
  const { data, isLoading: isPostLoading } = api.posts.getAll.useQuery();

  if (!userLoaded) return <div />;

  if (isPostLoading)
    return (
      <div className="flex grow">
        <LoadingPage />
      </div>
    );

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-none flex h-screen justify-center">
        <div className="flex h-full w-full flex-col border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!isSignedIn ? (
              <SignInButton mode="modal">
                <button className="btn flex justify-center">Sign in</button>
              </SignInButton>
            ) : (
              <SignOutButton>
                <button className="btn flex justify-center">Sign out</button>
              </SignOutButton>
            )}

            {isSignedIn && <CreatePostWizard />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
